version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: qr-code-mongodb
    ports:
      - "8060:27017" # Changed host port to 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
